import { z } from "zod";

const booleanFromEnv = (defaultValue: boolean) =>
  z.preprocess((value) => {
    if (value === undefined || value === null || value === "") {
      return defaultValue;
    }
    if (typeof value === "boolean") {
      return value;
    }
    if (typeof value === "string") {
      return value === "true" || value === "1";
    }
    return defaultValue;
  }, z.boolean());

const EnvSchema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  SESSION_SECRET: z.string().min(16),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().url(),
  S3_ENDPOINT: z.string().url(),
  S3_REGION: z.string().min(1).default("us-east-1"),
  S3_ACCESS_KEY: z.string().min(1),
  S3_SECRET_KEY: z.string().min(1),
  S3_BUCKET: z.string().min(1),
  S3_FORCE_PATH_STYLE: booleanFromEnv(true),
  S3_PUBLIC_BASE_URL: z.string().url().optional(),
  MAX_UPLOAD_MB: z.coerce.number().int().positive().default(250),
  STARTER_CREDITS: z.coerce.number().int().nonnegative().default(1000),
  ENABLE_URL_IMPORT: booleanFromEnv(true),
  ENABLE_PROJECTS_V2: booleanFromEnv(true),
  ENABLE_OPENCUT_EDITOR: booleanFromEnv(true),
  ENABLE_ENTERPRISE_SECURITY: booleanFromEnv(true),
  ENABLE_SSO: booleanFromEnv(true),
  ENABLE_API_KEY_SCOPES: booleanFromEnv(true),
  DESCRIPT_PLUS_ROLLOUT_STAGE: z.enum(["internal", "pilot", "small_team", "global"]).default("global"),
  DESCRIPT_PLUS_ROLLOUT_ALLOWLIST: z.string().default(""),
  DESCRIPT_PLUS_INTERNAL_DOMAIN: z.string().default("hookforge.local"),
  DESCRIPT_PLUS_AUTO_ROLLBACK: booleanFromEnv(true),
  DESCRIPT_PLUS_FORCE_ROLLBACK_TO_LEGACY: booleanFromEnv(false),
  DESCRIPT_PLUS_MIN_PARITY_SCORE: z.coerce.number().min(0).max(100).default(75),
  DESCRIPT_PLUS_MIN_RENDER_SUCCESS_PCT: z.coerce.number().min(0).max(100).default(99),
  DESCRIPT_PLUS_MIN_AI_SUCCESS_PCT: z.coerce.number().min(0).max(100).default(95),
  DESCRIPT_PLUS_MAX_QUEUE_BACKLOG: z.coerce.number().int().min(1).default(1200),
  DESCRIPT_PLUS_MAX_QUEUE_FAILED: z.coerce.number().int().min(0).default(200),
  DESCRIPT_PLUS_MAX_EDITOR_OPEN_P95_MS: z.coerce.number().int().min(100).default(2500),
  DESCRIPT_PLUS_MAX_COMMAND_P95_MS: z.coerce.number().int().min(10).default(100),
  OPENCUT_IMMEDIATE_REPLACEMENT: booleanFromEnv(true),
  OPENCUT_LEGACY_FALLBACK_ALLOWLIST: z.string().default(""),
  OPENCUT_EDITOR_COHORT: z.enum(["internal", "beta", "all"]).default("all"),
  OPENCUT_EDITOR_INTERNAL_DOMAIN: z.string().default("hookforge.local"),
  OPENCUT_EDITOR_BETA_ALLOWLIST: z.string().default(""),
  NEXT_PUBLIC_AI_EDITOR_DEFAULT: booleanFromEnv(true),
  NEXT_PUBLIC_SHOW_TEMPLATES_NAV: booleanFromEnv(false),
  NEXT_PUBLIC_QUICK_START_VISIBLE: booleanFromEnv(true),
  AI_EDITOR_DEFAULT_TEMPLATE_SLUG: z.string().min(1).default("green-screen-commentator"),
  ENABLE_LLM_RECIPE: booleanFromEnv(false),
  OPENAI_API_KEY: z.string().optional(),
  DEEPGRAM_API_KEY: z.string().optional(),
  ELEVENLABS_API_KEY: z.string().optional(),
  LIPSYNC_API_KEY: z.string().optional(),
  GENERATIVE_MEDIA_API_KEY: z.string().optional(),
  LIVEKIT_URL: z.string().url().optional(),
  LIVEKIT_API_KEY: z.string().optional(),
  LIVEKIT_API_SECRET: z.string().optional(),
  PUBLIC_API_KEY_SALT: z.string().optional(),
  TOP_LANGUAGES: z.string().default("en,es,fr,de,it,pt,ja,ko,hi,ar"),
  METRICS_NAMESPACE: z.string().default("hookforge")
});

export const env = EnvSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  SESSION_SECRET: process.env.SESSION_SECRET,
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_URL: process.env.REDIS_URL,
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_REGION: process.env.S3_REGION,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
  S3_SECRET_KEY: process.env.S3_SECRET_KEY,
  S3_BUCKET: process.env.S3_BUCKET,
  S3_FORCE_PATH_STYLE: process.env.S3_FORCE_PATH_STYLE,
  S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL,
  MAX_UPLOAD_MB: process.env.MAX_UPLOAD_MB,
  STARTER_CREDITS: process.env.STARTER_CREDITS,
  ENABLE_URL_IMPORT: process.env.ENABLE_URL_IMPORT,
  ENABLE_PROJECTS_V2: process.env.ENABLE_PROJECTS_V2,
  ENABLE_OPENCUT_EDITOR: process.env.ENABLE_OPENCUT_EDITOR,
  ENABLE_ENTERPRISE_SECURITY: process.env.ENABLE_ENTERPRISE_SECURITY,
  ENABLE_SSO: process.env.ENABLE_SSO,
  ENABLE_API_KEY_SCOPES: process.env.ENABLE_API_KEY_SCOPES,
  DESCRIPT_PLUS_ROLLOUT_STAGE: process.env.DESCRIPT_PLUS_ROLLOUT_STAGE,
  DESCRIPT_PLUS_ROLLOUT_ALLOWLIST: process.env.DESCRIPT_PLUS_ROLLOUT_ALLOWLIST,
  DESCRIPT_PLUS_INTERNAL_DOMAIN: process.env.DESCRIPT_PLUS_INTERNAL_DOMAIN,
  DESCRIPT_PLUS_AUTO_ROLLBACK: process.env.DESCRIPT_PLUS_AUTO_ROLLBACK,
  DESCRIPT_PLUS_FORCE_ROLLBACK_TO_LEGACY: process.env.DESCRIPT_PLUS_FORCE_ROLLBACK_TO_LEGACY,
  DESCRIPT_PLUS_MIN_PARITY_SCORE: process.env.DESCRIPT_PLUS_MIN_PARITY_SCORE,
  DESCRIPT_PLUS_MIN_RENDER_SUCCESS_PCT: process.env.DESCRIPT_PLUS_MIN_RENDER_SUCCESS_PCT,
  DESCRIPT_PLUS_MIN_AI_SUCCESS_PCT: process.env.DESCRIPT_PLUS_MIN_AI_SUCCESS_PCT,
  DESCRIPT_PLUS_MAX_QUEUE_BACKLOG: process.env.DESCRIPT_PLUS_MAX_QUEUE_BACKLOG,
  DESCRIPT_PLUS_MAX_QUEUE_FAILED: process.env.DESCRIPT_PLUS_MAX_QUEUE_FAILED,
  DESCRIPT_PLUS_MAX_EDITOR_OPEN_P95_MS: process.env.DESCRIPT_PLUS_MAX_EDITOR_OPEN_P95_MS,
  DESCRIPT_PLUS_MAX_COMMAND_P95_MS: process.env.DESCRIPT_PLUS_MAX_COMMAND_P95_MS,
  OPENCUT_IMMEDIATE_REPLACEMENT: process.env.OPENCUT_IMMEDIATE_REPLACEMENT,
  OPENCUT_LEGACY_FALLBACK_ALLOWLIST: process.env.OPENCUT_LEGACY_FALLBACK_ALLOWLIST,
  OPENCUT_EDITOR_COHORT: process.env.OPENCUT_EDITOR_COHORT,
  OPENCUT_EDITOR_INTERNAL_DOMAIN: process.env.OPENCUT_EDITOR_INTERNAL_DOMAIN,
  OPENCUT_EDITOR_BETA_ALLOWLIST: process.env.OPENCUT_EDITOR_BETA_ALLOWLIST,
  NEXT_PUBLIC_AI_EDITOR_DEFAULT: process.env.NEXT_PUBLIC_AI_EDITOR_DEFAULT,
  NEXT_PUBLIC_SHOW_TEMPLATES_NAV: process.env.NEXT_PUBLIC_SHOW_TEMPLATES_NAV,
  NEXT_PUBLIC_QUICK_START_VISIBLE: process.env.NEXT_PUBLIC_QUICK_START_VISIBLE,
  AI_EDITOR_DEFAULT_TEMPLATE_SLUG: process.env.AI_EDITOR_DEFAULT_TEMPLATE_SLUG,
  ENABLE_LLM_RECIPE: process.env.ENABLE_LLM_RECIPE,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  DEEPGRAM_API_KEY: process.env.DEEPGRAM_API_KEY,
  ELEVENLABS_API_KEY: process.env.ELEVENLABS_API_KEY,
  LIPSYNC_API_KEY: process.env.LIPSYNC_API_KEY,
  GENERATIVE_MEDIA_API_KEY: process.env.GENERATIVE_MEDIA_API_KEY,
  LIVEKIT_URL: process.env.LIVEKIT_URL,
  LIVEKIT_API_KEY: process.env.LIVEKIT_API_KEY,
  LIVEKIT_API_SECRET: process.env.LIVEKIT_API_SECRET,
  PUBLIC_API_KEY_SALT: process.env.PUBLIC_API_KEY_SALT,
  TOP_LANGUAGES: process.env.TOP_LANGUAGES,
  METRICS_NAMESPACE: process.env.METRICS_NAMESPACE
});
